# Generated by Django 4.0.2 on 2022-08-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_sent_job',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
