# Generated by Django 4.0.2 on 2022-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscription_last_sent_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
