# Generated by Django 4.0.2 on 2022-08-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscription_last_sent_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='last_sent_job',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
